# This Dockerfile MUST be built with the build context set to be the root of the
# mls-implementations repo.
#
# > docker build -f docker/test-runner/Dockerfile .
#
# Once this is built, you can run
FROM ubuntu:latest

RUN apt-get -y update && apt-get -y install git make golang protoc-gen-go

RUN useradd -m user
USER user
WORKDIR /home/user

# Set up Go prerequisites
ENV GOPATH=/home/user/go
ENV PATH=$PATH:$GOPATH/bin

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# Import this repo into the container
COPY --chown=user . mls-implementations
 
# Generate the Go interface from the proto files
WORKDIR mls-implementations/interop
RUN protoc --go_out=proto \
           --go_opt=paths=source_relative \
           --go-grpc_out=proto \
           --go-grpc_opt=paths=source_relative \
           -I proto \
           mls_client.proto

# Build the test runner
WORKDIR test-runner
RUN go build

ENTRYPOINT [ "./test-runner" ]
