---
name: mls-interop
services:
  openmls:
    build:
      dockerfile: ./Dockerfile.openmls
    ports:
      - 50051:${OPENMLS_PORT:-50051}
    command: -p ${OPENMLS_PORT:-50051}
  mlspp:
    build:
      dockerfile: ./Dockerfile.mlspp
    ports:
      - 50052:${MLSPP_PORT:-50052}
    command: -live ${MLSPP_PORT:-50052}
  test-runner:
    build:
      # Note that the context must be '..' so that the `interop` directory can
      # be copied into the container.
      context: ..
      dockerfile: ./docker/Dockerfile.test-runner
    command: -fail-fast -client openmls:${OPENMLS_PORT:-50051} -client mlspp:${MLSPP_PORT:-50052} -config=../configs/${CONFIG_RUN:-welcome_join.json}
